### ISSUE TITLE
Possible errata: rdf:HTML can be serialized.

### ISSUE THREAD

**Issue by afs** [w3c/rdf-xml#37]
https://www.w3.org/TR/rdf-xml/#section-Serialising
says that graph using rdf:HTML can not be serialized in RDF/XML.

It is true that the HTML can not be inlined, unlike rdf:XMLLiteral, but that does not stop it being serialized.

**Comment by gkellogg** [comment]
How about "Use the `rdf:HTML` datatype along with `rdf:parseTYpe="Literal"`?

Certainly, an existence proof that it can be serialized is something like `[ rdf:value "<span>foo</span"^^rdf:HTML ] .`

```
<?xml version='1.0' encoding='utf-8' ?>
<rdf:RDF xmlns:rdf='http://www.w3.org/1999/02/22-rdf-syntax-ns#'>
  <rdf:Description>
    <rdf:value rdf:datatype='http://www.w3.org/1999/02/22-rdf-syntax-ns#HTML'>&lt;span&gt;foo&lt;/span&gt;</rdf:value>
  </rdf:Description>
</rdf:RDF>
```

Alternatively, we could remove the entry, entirely.

**Comment by afs** [comment]
Removing is easier. Not being about to mix XML and HTML is a general fact, not specific to RDF. 

This isn't a document about `rdf:HTML` and `rdf:HTML` is not xHTML.

**Comment by TallTed** [comment]
> Removing is easier. Not being about to mix XML and HTML is a general fact, not specific to RDF.

s/Not being about/Not being able/

:-)
