### ISSUE TITLE
Fig. 2 does not pass WCAG AAA 

### ISSUE THREAD

**Issue by domel** [w3c/rdf-xml#43]
[Figure 2](https://w3c.github.io/rdf-xml/spec/figure2.svg) has #00000 as the foreground color and #FF0000 as the background color. It's unreadable, especially for people with vision problems.

**Comment by TallTed** [comment]
Helpful tools for this sort of thing --
* Accessible Web's [WCAG Color Contrast Checker](https://accessibleweb.com/color-contrast-checker/)
* WebAIM's [Contrast Checker](https://webaim.org/resources/contrastchecker/)

**Comment by domel** [comment]
@TallTed Yes, I tested it in these tools. The new one is proposed in https://github.com/w3c/rdf-xml/pull/44
