### ISSUE TITLE
This needs correcting 

### ISSUE THREAD

**Issue by Jayhelp** [w3c/rdf-xml#47]
I purchased this device, and initially it was working great. Now I barely receive notifications. Via third party apps and my Google voice number. Why has w3c structureef these components on my device. My location is showing extremely off in browser and my wifi shows excellent but my social apps aren't running. Please fix

http://www-ccpp.tcl-ta.com/files/t434d.xml

**Comment by pchampin** [comment]
Closing as off-topic.
